name: WWWDataManagement
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.9
  - psycopg2
  - flask-sqlalchemy
  - python-telegram-bot
  - flask-httpauth
  - pyjwt
  - requests
  - flask-cors
